name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  lint:
    name: Lint and format
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: lts/*
          args: --ignore-scripts
      - name: Run Eslint
        run: pnpm eslint "{src,apps,libs,test}/**/*.ts"
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: alford92
          POSTGRES_PASSWORD: mollit-non-dolor-laboris
          POSTGRES_DB: gullible-transparency
        ports:
          - "5432:5432"
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      integresql:
        image: allaboutapps/integresql
        env:
          PGUSER: alford92
          PGPASSWORD: mollit-non-dolor-laboris
          PGDATABASE: gullible-transparency
          PGHOST: postgres
          PGPORT: "5432"
          PGSSLMODE: disable
        ports:
          - "5000:5000"
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Setup PNPM
        uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: lts/*
          args: --frozen-lockfile
      - name: Run tests
        run: pnpm test
        env:
          POSTGRES_USER: alford92
          POSTGRES_PASSWORD: mollit-non-dolor-laboris
          POSTGRES_DB: gullible-transparency
          POSTGRES_HOST: localhost
          INTEGRESQL_BASE_URL: http://localhost:5000
